- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    STATE_RES_NAME: ami_info
    VPC_SUBNET_CIDR_BLOCK: "${VPC_SUBNET_CIDR_BLOCK}"
    VPC_CIDR_BLOCK: "${VPC_CIDR_BLOCK}"
    VPC_NAME: "${VPC_NAME}"
    VPC_ID: "${VPC_ID}"
    VPC_SUBNET_ID: "${VPC_SUBNET_ID}"
    VPC_IGW_ID: "${VPC_IGW_ID}"
  tasks:
    - name: Delete RT for VPC {{ VPC_NAME }}
      ec2_vpc_route_table:
        vpc_id: "{{ VPC_ID }}"
        tags:
          Name: Public
        subnets:
          - "{{ VPC_SUBNET_ID }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ VPC_IGW_ID }}"
        state: absent

    - name: Delete Public SG group
      ec2_group:
        name: publicSG
        description: Public access Security Group
        vpc_id: "{{ VPC_ID }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ VPC_SUBNET_CIDR_BLOCK }}"
        state: absent

    - name: Delete Subnet for VPC {{ VPC_NAME }}
      ec2_vpc_subnet:
        vpc_id: "{{ VPC_ID }}"
        cidr: "{{ VPC_SUBNET_CIDR_BLOCK }}"
        state: absent

    - name: Delete internet gateway for VPC {{ VPC_NAME }}
      ec2_vpc_igw:
        vpc_id: "{{ VPC_ID }}"
        state: absent

    - name: Delete VPC {{ VPC_NAME }}
      ec2_vpc_net:
        state: absent
        name: "{{ VPC_NAME }}"
        cidr_block: "{{ VPC_CIDR_BLOCK }}"
        tags:
          module: "{{ VPC_NAME }}"
        tenancy: dedicated
      register: vpc
